services:
  create_link_files:
    build: .
    volumes:
      - "nextcloud_aio_nextcloud_data:/usr/src/app/data"
    environment:
      - version: "v1.01"
volumes:
  nextcloud_aio_nextcloud_data:
    external: true

#RUN --mount=type=volume,source=nextcloud_aio_nextcloud_data,target=/usr/src/app/data,rw