services:
  create_link_files:
    build: .
    volumes:
      - "nextcloud_aio_nextcloud_data:/usr/src/app/data"
    environment:
      VERSION: v1.01
volumes:
  nextcloud_aio_nextcloud_data:
    external: true