services:
  create_link_files:
    image: chr1sn0/create_link_files
    volumes:
      - "nextcloud_aio_nextcloud_data:/usr/src/app/data"
    environment:
      VERSION: v1.02
volumes:
  nextcloud_aio_nextcloud_data:
    external: true